name: Test Suite

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - uses: actions/checkout@v2
    - name: Install with test dependencies
      shell: bash
      run: |
        python setup.py develop
        python -m pip install -r requirements-test.txt
    - name: Run test suite
      run: |
        py.test
    - name: Check with flake8
      run: |
        python -m pip install flake8
        python -m flake8 peggie tests
    - name: Check black code style used
      run: |
        python -m pip install black
        python -m black --check peggie tests
